### Numeric python

In [2]:
import numpy as np

In [3]:
arr = np.array([12,23,45,56,32])

In [4]:
arr

array([12, 23, 45, 56, 32])

In [5]:
print(arr)

[12 23 45 56 32]


In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.dtype

dtype('int32')

In [8]:
arr = np.array([12,23,45,56,32,66.22,'pune'])

In [9]:
arr.dtype #or we also write only arr for finding data type 

dtype('<U32')

In [10]:
%%timeit   # to find how much time is token for run this cell
arr = np.array([12,23,45,56,32,66.22,'pune'])

6.79 µs ± 49.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [11]:
arr[3]

'56'

In [12]:
arr[-1]

'pune'

In [13]:
arr.shape

(7,)

In [14]:
arr = np.array([12,23,45,56,32])

In [15]:
arr*2

array([ 24,  46,  90, 112,  64])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [19]:
np.arange(2,5,7)

array([2])

In [20]:
np.arange(1.5,5.5)

array([1.5, 2.5, 3.5, 4.5])

In [21]:
np.arange(-5,5,0.5)

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 2d Array

In [24]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [25]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [26]:
arr1.shape

(4, 3)

In [27]:
arr1.ndim

2

In [29]:
arr1.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr1

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr1.shape

(4, 3)

In [32]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
arr1.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [34]:
arr1.reshape(6,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [35]:
arr1.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [36]:
arr1.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [37]:
arr1.reshape(4,3,-1)

array([[[ 1],
        [ 2],
        [ 3]],

       [[ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12]]])

In [38]:
arr.min()

12

In [39]:
arr.max()

56

In [40]:
arr= np.array([1,3,5,6,3,3,1,7])

In [41]:
np.unique(arr)

array([1, 3, 5, 6, 7])

In [42]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.linalg.det(arr1)

6.66133814775094e-16

In [45]:
np.linalg.inv(arr1)

array([[-4.50359963e+15,  9.00719925e+15, -4.50359963e+15],
       [ 9.00719925e+15, -1.80143985e+16,  9.00719925e+15],
       [-4.50359963e+15,  9.00719925e+15, -4.50359963e+15]])

In [46]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [47]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr1*arr2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [51]:
s = 'hii'

In [52]:
s[::-1]

'iih'