##### Q.1) Create a package named 'cricket' which will contain modules named batsman & bowler.
##### Create following functions in respective modules.
##### Import the package and call all these functions in your program
##### batsman: findaverage(runs,matches) , strikerate(runs,balls)
##### bowler: findavg(runs,wicket), economyrate(overs,runs)

In [1]:
from cricket import batsman,bowler

print('FOR BATSMAN')

runs = int(input('Enter runs:'))
matches = int(input('Enter matches:'))
balls = int(input('Enter balls:'))

print('Batsman average=',batsman.findaverage(runs,matches))

print('Batsman strikerate=',batsman.strikerate(runs,balls))

print('')

print('FOR BOWLER')

runs = int(input('Enter runs:'))
wicket = int(input('Enter wickets:'))
overs = int(input('Enter overs:'))

print('Bowler average=',bowler.findavg(runs,wicket))

print('Bowler economyrate=',bowler.economyrate(overs,runs))

FOR BATSMAN


Enter runs: 100
Enter matches: 3
Enter balls: 50


Batsman average= 33.333333333333336
Batsman strikerate= 200.0

FOR BOWLER


Enter runs: 50
Enter wickets: 4
Enter overs: 3


Bowler average= 12.5
Bowler economyrate= 16.666666666666668


##### Q.2) Write a python function to find whether number is prime or not
##### def isPrime(num)

In [2]:

def isPrime(num):
    if num > 1:
        for i in range(2, (num //2)+1):
            if(num % i) == 0:
                print('not a prime number')
                break
            else:
                print('prime number')
    else:
        print('not prime number')

In [3]:
isPrime(5)

prime number


In [4]:
isPrime(4)

not a prime number


##### Q.3) Write a function is_palindrome(string) that takes a string as input and returns True if the string reads the same backward as forward
##### eg. "racecar" is a palindrome

In [5]:
def is_palindrome(string):
    if string == string[::-1]:
        print(string,'is palindrome')
    else:
        print(string,'is not palindrome')

In [6]:
is_palindrome('racecar')

racecar is palindrome


In [7]:
is_palindrome('hello')

hello is not palindrome


##### Q.4) Write a function reverse_list(data) that takes a list as input and returns a new list with elements in reverse order

In [8]:
data = [12, 23, 34, 45, 56, 67]

def reverse_list(data):
    print(data[::-1])

In [9]:
reverse_list(data)

[67, 56, 45, 34, 23, 12]


##### Q.5) Write a function write_file(filename, content) that takes a filename and content as input and writes the content to the specified file

In [10]:
def write_file(filename,content):
    with open(filename, 'w') as f:
     f.write(content)

In [11]:
content='This is 1st line.\n This 2nd line.\nThis is 3rd line'

write_file('week2', content)

##### Q.6)  Write a function copy_file(source_filename, destination_filename) that takes the source and destination filenames as input and copies the contents of the source file to destination file. Handle cases where the source file doesn't exist

In [12]:
def copy_file(source_filename, destination_filename):
    with open('source.txt','r') as s, open('destination.txt','w') as d:
        
        for line in s:
            d.write(line)

In [13]:
copy_file('source.txt','destination.txt')

##### Q.7) Implement a function to calculate the dot product of two NumPy arrays

In [14]:
import numpy as np

def dot_product(arr1 , arr2):
    result = np.dot(arr1,arr2)
    return(result)

array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
res = dot_product(array1,array2)
print('Dot product of arrays= \n',res)

Dot product of arrays= 
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


##### Q.8) Implement a GUI with a radio button selection for choosing a favorite colour.Change a background color of the window based on the selected radio button

In [15]:
import tkinter as tk
from tkinter import ttk

In [16]:
def change_color():
    selected_color = color_var.get()
    top.configure(bg=selected_color)

top= tk.Tk()
top.title('color selection')
top.geometry('300x200')

color_var = tk.StringVar()

colors = ['Pink','Sky Blue','Lavender','Crimson','Orange']
for color in colors:
    radio_button = ttk.Radiobutton(top, text=color, value=color, variable=color_var,command = change_color)
    radio_button.pack(anchor=tk.W)

color_var.set(colors[0])
top.configure(bg=colors[0])

top.mainloop()

##### Q.9) Design a currency converter in GUI.Allow users to enter an amount and select the currencies they want to convert between(eg.USD,EUR).Display the converted amount in the selected currency

In [17]:
import tkinter as tk
from tkinter import ttk

# Fixed exchange rates for simplicity
exchange_rates = {
    "USD": {"EUR": 0.85, "USD": 1, "GBP": 0.75},
    "EUR": {"USD": 1.18, "EUR": 1, "GBP": 0.88},
    "GBP": {"USD": 1.34, "EUR": 1.14, "GBP": 1},
}

def convert_currency():
    try:
        amount = float(amount_entry.get())
        from_currency = from_currency_var.get()
        to_currency = to_currency_var.get()
        rate = exchange_rates[from_currency][to_currency]
        converted_amount = amount * rate
        result_var.set(f"{converted_amount:.2f} {to_currency}")
    except ValueError:
        result_var.set("Invalid amount entered")

# Create the main window
top = tk.Tk()
top.title("Currency Converter")
top.geometry("400x200")

# Amount entry
tk.Label(top, text="Amount:").grid(row=0, column=0, padx=10, pady=10)
amount_entry = tk.Entry(top)
amount_entry.grid(row=0, column=1, padx=10, pady=10)

# From currency selection
tk.Label(top, text="From:").grid(row=1, column=0, padx=10, pady=10)
from_currency_var = tk.StringVar(value="USD")
from_currency_menu = ttk.Combobox(top, textvariable=from_currency_var, values=list(exchange_rates.keys()))
from_currency_menu.grid(row=1, column=1, padx=10, pady=10)

# To currency selection
tk.Label(top, text="To:").grid(row=2, column=0, padx=10, pady=10)
to_currency_var = tk.StringVar(value="EUR")
to_currency_menu = ttk.Combobox(top, textvariable=to_currency_var, values=list(exchange_rates.keys()))
to_currency_menu.grid(row=2, column=1, padx=10, pady=10)

# Convert button
convert_button = tk.Button(top, text="Convert", command=convert_currency)
convert_button.grid(row=3, column=0, columnspan=2, padx=10, pady=10)

# Result label
result_var = tk.StringVar()
result_label = tk.Label(top, textvariable=result_var)
result_label.grid(row=4, column=0, columnspan=2, padx=10, pady=10)

# Run the main loop
top.mainloop()